server:
  port: 8181

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: wgstar
    password: wgstar

  jpa:
    hibernate:
      ddl-auto: update
      #only for develop purposes
      #ddl-auto: create


logging:
  level:
    org.springframework.cloud: 'INFO'
    org.springframework.security: 'INFO'
    org.hibernate.SQL: 'DEBUG'